name: Laravel Tests

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    
    #Checkout code
    - uses: actions/checkout@v2
    
    #Prepare laravel's .env file
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Set up artifactory access on composer
    - name: Configure artifactory access
      run: |
        echo "{\"http-basic\":{\"artifactory.ops.neta.sh\":{\"username\":\"github-actions\",\"password\":\"${ARTIFACTORY_SECRET}\"}}}" > auth.json
      env:
        ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}

    # Fetch all dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    
    - name: Remove auth.json file
      run: rm auth.json
   
    - name: Generate key
      run: php artisan key:generate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
